# Write a Python program to convert a list of numeric value into a one-dimensional NumPy array. 
Expected Output:
Original List: [12.23, 13.32, 100, 36.32] 
One-dimensional numpy array: [ 12.23 13.32 100. 36.32] 




In [9]:
import numpy as np
print("Original List :: ")
a = [12.23, 13.32, 100, 36.32]
print(a)
print("One-dimensional numpy array:::")
np.asarray(a)


Original List :: 
[12.23, 13.32, 100, 36.32]
One-dimensional numpy array:::


array([ 12.23,  13.32, 100.  ,  36.32])

# Create a 3x3 matrix with values ranging from 2 to 10. 
Expected Output:
[[ 2 3 4] 
[ 5 6 7] 
[ 8 9 10]] 




In [19]:
import numpy as np
A = np.random.randint(2,10,size=(3,3))
print(A)

[[2 7 2]
 [7 4 7]
 [7 9 6]]


# Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
Update sixth value to 11 
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [20]:
import numpy as np
N= np.zeros(10)
print(N)
print("Update sixth value to 11")
N[6] = 11
print(N)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
